### ISSUE TITLE
Trailing whitespace in comments should be linted

### ISSUE THREAD

**Issue by a-frantz** [stjude-rust-labs/wdl#174]
This check should be added to an existing rule, probably `CommentWhitespace` or maybe just the generic `Whitespace` rule. It should trigger for all comments (lint directives, preamble comments, and "regular" comments).

**Comment by BradenEverson** [comment]
I'd be interested in taking this on! Does this rule live in the `comment_whitespace.rs` file in `wdl-lint`? 

I might need a bit of an explanation of how this is all working, but it looks like the `Visitor` implementation is what's doing the actual checking?

**Comment by a-frantz** [comment]
It could reasonably fit `comment_whitespace.rs`, but I think a slightly better fit would be in https://github.com/stjude-rust-labs/wdl/blob/main/wdl-lint/src/rules/whitespace.rs

But yes, the `Visitor` impl is what does the heavy lifting for linting. We (and by we I mean Peter) have architected it so that all the lint rules are enforced with one pass through the syntax tree. The syntax tree is made up of "nodes" and "tokens". Each node will be visited twice, once on `Enter` and once on `Exit`. Each "token" is visited only once.

You'll want to add a comment visitor to `whitespace.rs` that checks for trailing whitespace. Comments are tokens, so are only visited once.

Feel free to reach out either on this issue or over Slack if you need some more direction!

**Comment by BradenEverson** [comment]
Okay makes sense, I'll get started on this all sometime today or tomorrow and let you know if I have any questions over slack, thanks!
