### ISSUE TITLE
New RedundantAssignment rule

### ISSUE THREAD

**Issue by a-frantz** [stjude-rust-labs/wdl#189]
Upgrading discussion #105 to an issue for visibility. See the linked discussion for more details, but any conversation about this rule should occur here.

**Comment by michaelgattas** [comment]
@a-frantz I'm happy to take this one on!

**Comment by a-frantz** [comment]
@michaelgattas all yours!

I wasn't explicit about this small complication, but this rule is going to need to check the version of the document, and only fire if the version is >=v1.1 (i.e. this should be silent in 1.0 documents). There are examples of other rules checking the version, so you can just follow those examples (`missing_runtime.rs` is one of those examples).

**Comment by michaelgattas** [comment]
@a-frantz do you think this should this create a Warning or Note diagnostic?

**Comment by a-frantz** [comment]
> @a-frantz do you think this should this create a Warning or Note diagnostic?

I think this is `note` territory. The more verbose syntax isn't a source of confusion.
