### ISSUE TITLE
feature request: incorporate shellcheck for linting command blocks

### ISSUE THREAD

**Issue by a-frantz** [stjude-rust-labs/wdl#191]
This feature will be a complete rip-off from miniwdl. It's my favorite feature of `miniwdl check` and I want us to copy it.

For completeness: link to [`shellcheck` site](https://www.shellcheck.net/)

It's been a while since I looked into this, but when I last looked there wasn't a good Rust crate for doing Bash linting. `miniwdl` shells out to `shellcheck` and parses the resulting STDOUT for a nice user interface. We are probably going to be stuck doing the same, which isn't ideal bc it's not very robust. But linting command blocks is a great feature I really want us to have, and it's worth getting our hands a little dirty IMO.

**Comment by thatRichman** [comment]
Very selfishly interested in this. I might be able to take a stab at it if this is still desired. Would I be correct in thinking this would be more appropriate for sprocket now?

**Comment by a-frantz** [comment]
We would certainly welcome that contribution! I've wanted this feature for a long time, but it hasn't made it up high enough in my priority list.

I think this code should live in the `wdl-lint` crate, not `sprocket`.

**Comment by claymcleod** [comment]
Yeah I'd say this should live in `wdl-lint` as well. It's probably a "not on by default" lint that you have to opt in to. This will be quite a tricky one to implement gracefully—feel free to drop into the Zulip channel pointed to in the `README.md` to discuss with us!

**Comment by thatRichman** [comment]
Sure, would be happy to discuss! Looks like the linked Zulip channel is invite only, though.

**Comment by claymcleod** [comment]
Oh, thanks for pointing that out! I've updated the link with the invitation code—could you try again?
