### ISSUE TITLE
reported span when missing comma not helpful

### ISSUE THREAD

**Issue by a-frantz** [stjude-rust-labs/wdl#67]
Here's an example:
```
error: parse error
    ┌─ ./tools/util.wdl:385:13
    │
385 │             help: "`choices` below are the possible values from a GENCODE GTF file. If you are using a different GTF source, you may need to adjust this parameter.",
    │             ^ The following tokens are required: comma.
```
Created from WDL code:
```
    parameter_meta {
        gtf: "Gzipped GTF feature file from which to derive a coverage regions BED file"
        feature_type: {
            description: "Feature type to filter on. Only lines with this feature type will be included in the output BED file."
            help: "`choices` below are the possible values from a GENCODE GTF file. If you are using a different GTF source, you may need to adjust this parameter.",
            choices: [
                "gene",
                "transcript",
                "exon",
                "CDS",
                "UTR",
                "start_codon",
                "stop_codon",
                "Selenocysteine"
            ]
        }
        outfile_name: "Name of the output BED file"
        modify_disk_size_gb: "Add to or subtract from dynamic disk space allocation. Default disk size is determined by the size of the inputs. Specified in GB."
    }
```
The line printed (385) by sprocket is ok, it's the unprinted line prior (384) which is missing a comma.

**Comment by peterhuene** [comment]
Guidance on how to address this in the new parser implementation:

The new parser has a [delimited method](https://github.com/stjude-rust-labs/wdl/blob/main/wdl-grammar/src/experimental/parser.rs#L578) on it, where it attempts to parse (via a callback) a node that may have a required delimiter in-between the nodes, such as a comma.

Currently we call [expect](https://github.com/stjude-rust-labs/wdl/blob/main/wdl-grammar/src/experimental/parser.rs#L616-L619) for the delimiter, which will add a diagnostic of "expected \<delimiter>, but found \<found>" pointing to the span of what was found, not unlike the existing parser implementation.

To fix this, I think we could peek to see if the delimiter is present, and if it isn't, we search from the back of the parser event list for a token that isn't trivia (i.e. `!T::is_trivia(token)`) and we use span of the token's end position plus 1 with a length of 1 to indicate where we think the delimiter token should go.
